#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/simulation

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/simulation

OBJ_DEBUG = $(OBJDIR_DEBUG)/sbm.o $(OBJDIR_DEBUG)/randomGenerator.o $(OBJDIR_DEBUG)/mcSimulation.o $(OBJDIR_DEBUG)/mcPresenter.o $(OBJDIR_DEBUG)/abstractGraph.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/histogram.o $(OBJDIR_DEBUG)/er.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/sbm.o $(OBJDIR_RELEASE)/randomGenerator.o $(OBJDIR_RELEASE)/mcSimulation.o $(OBJDIR_RELEASE)/mcPresenter.o $(OBJDIR_RELEASE)/abstractGraph.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/histogram.o $(OBJDIR_RELEASE)/er.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/sbm.o: sbm.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sbm.cpp -o $(OBJDIR_DEBUG)/sbm.o

$(OBJDIR_DEBUG)/randomGenerator.o: randomGenerator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c randomGenerator.cpp -o $(OBJDIR_DEBUG)/randomGenerator.o

$(OBJDIR_DEBUG)/mcSimulation.o: mcSimulation.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c mcSimulation.cpp -o $(OBJDIR_DEBUG)/mcSimulation.o

$(OBJDIR_DEBUG)/mcPresenter.o: mcPresenter.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c mcPresenter.cpp -o $(OBJDIR_DEBUG)/mcPresenter.o

$(OBJDIR_DEBUG)/abstractGraph.o: abstractGraph.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c abstractGraph.cpp -o $(OBJDIR_DEBUG)/abstractGraph.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/histogram.o: histogram.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c histogram.cpp -o $(OBJDIR_DEBUG)/histogram.o

$(OBJDIR_DEBUG)/er.o: er.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c er.cpp -o $(OBJDIR_DEBUG)/er.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/sbm.o: sbm.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sbm.cpp -o $(OBJDIR_RELEASE)/sbm.o

$(OBJDIR_RELEASE)/randomGenerator.o: randomGenerator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c randomGenerator.cpp -o $(OBJDIR_RELEASE)/randomGenerator.o

$(OBJDIR_RELEASE)/mcSimulation.o: mcSimulation.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c mcSimulation.cpp -o $(OBJDIR_RELEASE)/mcSimulation.o

$(OBJDIR_RELEASE)/mcPresenter.o: mcPresenter.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c mcPresenter.cpp -o $(OBJDIR_RELEASE)/mcPresenter.o

$(OBJDIR_RELEASE)/abstractGraph.o: abstractGraph.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c abstractGraph.cpp -o $(OBJDIR_RELEASE)/abstractGraph.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/histogram.o: histogram.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c histogram.cpp -o $(OBJDIR_RELEASE)/histogram.o

$(OBJDIR_RELEASE)/er.o: er.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c er.cpp -o $(OBJDIR_RELEASE)/er.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

